branches: [ master, develop ]

pipeline:
  docker:
    image: plugins/docker
    repo: mikeifomin/rtak
    secrets: [ docker_username, docker_password ]
    force_tag: true
    tags:
      - ${DRONE_TAG}
      - latest
    when:
      event: tag
